### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by tanoury1** [ahashemiche/ReNeGate#1]
Hi,
I am trying to build ReNeGate.  I have all the dependencies installed.  When I try to run make, I get the following error:

[tanoury@tanourylnx:ReNeGate]$ make -f Makefile
mkdir -p obj/./src/
cc -Wall -c src/comfunct.c -o obj/./src/comfunct.c.o
src/comfunct.c: In function ‘get_nb_atomIn’:
src/comfunct.c:937:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < size; i++){
  ^
src/comfunct.c:937:2: note: use option -std=c99 or -std=gnu99 to compile your code
src/comfunct.c: In function ‘get_nb_bonds’:
src/comfunct.c:948:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < size; i++){
  ^
src/comfunct.c:949:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int j = i+1; j < size; j++){
   ^
make: *** [obj/./src/comfunct.c.o] Error 1

How can I fix this?

Thank  you,
Jerry

**Comment by tanoury1** [comment]
Figured it out.  Need to use '-std=gnu99' instead of '-std=c99'.  And I had to create ReNeGate/bin manually, otherwise I got an error saying bin/singanalysis could not be found.

**Comment by tanoury1** [comment]
The build completed without error, but I did not get a 'conformer_explorer' file.  I have CREST installed in a separate location and made it part of PATH before building ReNeGate.  How do I get conformer.explorer?

Jerry

**Comment by ahashemiche** [comment]
Hi Jerry,

Thanks for bringing it to notice. I have renamed it in the last modifications to "CREST_explorer.sh". You can use this bash script to submit your exploration job.

I will do modifications to the instructions solve this confusion. 
Ali

**Comment by ahashemiche** [comment]
> Figured it out. Need to use '-std=gnu99' instead of '-std=c99'. And I had to create ReNeGate/bin manually, otherwise I got an error saying bin/singanalysis could not be found.

True. This is fixed now. 
Thanks
Ali
